---
- name: Configurar servidor do banco de dados
  hosts: db001
  
  user: vagrant
  become: yes
  var_files:
    - vars/main.yml
  vars:
    - dbname: "db001"
    - dbusername: "root"
    - dbpassword: "devops"
  tasks:
    - name: Configurar hosts lab ansible
      lineinfile: line "{{item}}" path=/etc/hosts
      with_items:
        - 192.168.1.2 control-node
        - 192.168.1.3 app001
        - 192.168.1.4 db001
  roles:
    - configuracao-default-so
    - role: geerlingguy.mysql