Vagrant.configure("2") do |config|

  config.vm.box = "base"

  config.vm.hostname = "db001"

  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.3"

  config.vm.network "private_network", ip: "192.168.33.10"

end
